[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

# Optional: increase timeout on Pro, and force correct headers for functions
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
